name: docker-tests
on:
  push:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
env:
  JAVA_VERSION: 8
jobs:
  docker-tests:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.docker
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml', '**/docker-compose.yaml') }}
      - run: command -v docker >/dev/null 2>&1 || { echo >&2 "Docker is required but not installed.  Aborting."; exit 1; }
      - run: cd $GITHUB_WORKSPACE ; ./mvnw -Pdocker docker-compose:up
      - run: docker ps
      - run: cd $GITHUB_WORKSPACE ; ./mvnw -Pdocker docker-compose:down
