name: github-pages
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
  push:
    branches: ['master']
  pull_request:
permissions:
  contents: write
env:
  JAVA_VERSION: 8
jobs:
  github-pages:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # 'temurin' 'zulu' 'adopt' 'adopt-hotspot' 'adopt-openj9' 'liberica' 'microsoft'
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.docker
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml', '**/docker-compose.yaml') }}
      - run: cd $GITHUB_WORKSPACE ; ./mvnw clean ; ./mvnw -Pdocs
      - name: Deploy 🚀 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/generated-docs
          branch: gh-pages
          clean: true
